### ISSUE TITLE
Capture successful but playback failing

### ISSUE THREAD

**Issue by leppert** [loucks1/Directolor#7]
First, thanks for such a great library. I'm working on getting it booted up but have hit a wall. It appears I'm able to capture codes from my remote but, when attempting to play them back, I get no response from my blinds. Below is what I see in the Serial Monitor when running `search` and then pressing "stop" on my remote, then sending `dump`, and then `o` to try to open the blinds. Pressing other buttons on the remote (open, tilt open, etc) result in them being captured and printed to the monitor.

I've double checked my wiring and it all appears to be correct but I'm not sure if it's safe to assume that being able to capture codes means the wiring is correct for transmission as well.

FWIW, this is my [ESP32](https://www.amazon.com/gp/product/B077KJNVFP/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1) and this is my [NRF24L01+](https://www.amazon.com/gp/product/B01IK78PQA/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1)

As an aside, I wasn't sure if the instructions in the README are correct and I [only need to press the stop button once](https://github.com/loucks1/Directolor/blob/main/README.md?plain=1#L31) before dumping or if the instructions at the top of GetBlindCodes are correct and I [need to press all of the buttons three times before dumping](https://github.com/loucks1/Directolor/blob/main/Directolor/examples/GetBlindCodes/GetBlindCodes.ino#L7).

```
bytes: 3 pipe: 1:  00 00 41 02 
�Commands available:
(search) remote - enter Remote Search Mode
(dump) codes    - dump the remote code so you can put into directolor.h (only valid if you've captured a remote code using search)
(o)pen blind    - send open code for current channel(s)
(c)lose blind   - send close code for current channel(s)
(s)top blind    - send stop code for current channel(s)
(j)oin blind    - send join code for current channel
(r)emove blind  - send remove code for current channel
(remote #)      - set remote number
(channel #)     - set channel number
(help)          - show this screen


Remote = 1, Channel = 1
Attempting to initialize radio - CE Pin:22 CS Pin:21
Attempting to start radio
Radio started
searching for remote
...
Found Remote with address:  CB CB C0
Capture Mode
bytes: 20 pipe: 1:  11 00 05 9B FF FF F3 E5 86 06 9F 01 00 F3 E5 52 53 00 6A 37 AA Stop
/*
* Radio:  CB CB F3 E5
*/
,{ 
  {0xCB, 0xCB, 0xF3, 0xE5}}
Remote 1, Channels: 1-Open
32 55 55 55 55 55 55 55 55 55 12 F0 C0 11 00 05 08 FF FF 78 09 86 06 1D 01 00 78 09 52 55 00 B7 5E
280
Capture Mode
32 55 55 55 55 55 55 55 55 55 12 F0 C0 11 00 05 A0 FF FF 78 09 86 06 54 01 00 78 09 52 55 00 B7 47
280
Capture Mode
32 55 55 55 55 55 55 55 55 55 12 F0 C0 11 00 05 2D FF FF 78 09 86 06 03 01 00 78 09 52 55 00 5E 07
280
Capture Mode
```

**Comment by leppert** [comment]
After searching around, it looks like the NRF24L01+ I'm using (with external antenna) might not be getting enough power. Ordered a module with integrated antenna and will update once I've given that a try.

**Comment by loucks1** [comment]
Thanks for reaching out.  I can see I need to update the instructions.  I've made changes to how this whole thing works and apparently didn't update the readme.   Sorry for the time you've spent going down the wrong path.  If you can receive, you should definitely be able to send. 

You can always join a blind to one of the existing channels and then use open / close from there.

That being said, you've done all the hard work already.   Simply:

1. Update Directolor.h with your radio code.  Here is the line from your results above:

```
/*
* Radio:  CB CB F3 E5
*/
,{ 
  {0xCB, 0xCB, 0xF3, 0xE5}}
```

Find:  
```
/*
* Radio:  12 F0 78 09
*/
{{0x12, 0xF0, 0x78, 0x09}}
```
In Directolor.h and replace it with your code above.  It will end up looking something like:

```
const RemoteCode remoteCodes[DIRECTOLOR_REMOTE_COUNT] =
        {
            /*
             * Radio:  CB CB F3 E5
             */
            {0xCB, 0xCB, 0xF3, 0xE5}}
            /*
             * Radio:  11 11 B9 7B
             */
           ,
```

You should be able to then control your blinds by doing (o)pen or (c)lose.

I would try with your module close to the blind and get that working before you order the other part.

Definitely keep me updated on your progress.

**Comment by loucks1** [comment]
Also, it defaults to Remote 1, Channel 1.  You updated remote 1 above, but say you are using button 3 on the remote, you would need to specify channel 3 before attempting blind actions (o)pen, (s)top, etc.

**Comment by leppert** [comment]
Thank you! I updated `Directolor.h` and can see that, when I compile and then run commands, it defaults to the radio I pasted in without needing to search / capture the remote first:

```
Remote = 1, Channel = 1
Attempting to initialize radio - CE Pin:22 CS Pin:21
Attempting to start radio
Radio started
Remote 1, Channels: 1-Open
32 55 55 55 55 55 55 55 55 55 CB CB C0 11 00 05 67 FF FF F3 E5 86 06 E8 01 00 F3 E5 52 55 00 E6 1B
278
32 55 55 55 55 55 55 55 55 55 CB CB C0 11 00 05 E2 FF FF F3 E5 86 06 18 01 00 F3 E5 52 55 00 76 11
278
32 55 55 55 55 55 55 55 55 55 CB CB C0 11 00 05 C7 FF FF F3 E5 86 06 8D 01 00 F3 E5 52 55 00 C8 B1
278
Remote 1, Channels: 1-Open
32 55 55 55 55 55 55 55 55 55 CB CB C0 11 00 05 FD FF FF F3 E5 86 06 3C 01 00 F3 E5 52 55 00 FF 7B
280
32 55 55 55 55 55 55 55 55 55 CB CB C0 11 00 05 7D FF FF F3 E5 86 06 E3 01 00 F3 E5 52 55 00 99 37
280
32 55 55 55 55 55 55 55 55 55 CB CB C0 11 00 05 98 FF FF F3 E5 86 06 CA 01 00 F3 E5 52 55 00 67 B4
280
Remote 1, Channels: 1-Close
32 55 55 55 55 55 55 55 55 55 CB CB C0 11 00 05 B5 FF FF F3 E5 86 06 65 01 00 F3 E5 52 44 00 07 8F
```

Unfortunately, still no action from the blinds themselves. If it's helpful context, I only have one group of them (6 blinds in total) and they're all mapped to channel 1. It's a sunroom and the blinds are mounted 10ft up (which is why we went for motorized blinds) so I'm only able to sit beneath them with about an 8ft vertical, unobscured distance between the radio and the blind header. Is it safe to assume that should be close enough for testing?

With regards to the readme, no worries on the lost time—I can only imagine how long it took you to write the library so I didn't have to! But I was left wondering if, at least for now, the notes in `GetBlindCodes` are the correct procedure or if the README is the place to look. To put a finer point on my question, should I expect different output from a dump performed with one press of the stop button vs three presses of every button before dumping?

**Comment by loucks1** [comment]
I have mine setup to work fine about 50 feet away going through 5 walls.  

Can you provide me a link to purchase the radio module you are using? (preferably Amazon)  I'd like to get one and play with it.  If you can receive, you really should be able to send.

The readme is better than GetBlindCodes for sure.  You don't need to press each button 3 times.  All you should need is the radio code.  You should not expect a different output anymore.

**Comment by leppert** [comment]
Thanks so much. Here's my ESP32:

HiLetgo ESP32 ESP-32 ESP-32S ESP32S WiFi Bluetooth Wireless Board Module Based ESP-WROOM-32 Dual Core Mode CPU https://a.co/d/aIcV2f8

And here is my NRF24L01+:

MakerFocus 2pcs NRF24L01+PA+LNA Wireless Transceiver RF Transceiver Module 2.4G 1100m with Antenna in Antistatic Foam Compatible Ar duino https://a.co/d/dmITu90

**Comment by leppert** [comment]
I just connected this NRF24L01+ with PCB antenna (vs the external antenna of the previous module) and everything works swimmingly. Thank you so much!

https://www.amazon.com/dp/B00LX47OCY?psc=1&ref=ppx_yo2ov_dt_b_product_details

**Comment by loucks1** [comment]
Very glad to hear that it is working for you.  I should have the other modules here on Tuesday and I'll re-open this issue if I figure something out.
