### ISSUE TITLE
Question: Can I use directolor without the original remote?

### ISSUE THREAD

**Issue by Roku38** [loucks1/Directolor#9]
Is it possible to sync directolor with the blinds without the physical remote?

**Comment by loucks1** [comment]
yes - there are 6 'built-in' remotes in directolor by default.  you can (J)oin any of those to any blind.  use the (remote #) command and (channel #) command to choose which remote is active before you use the (J)oin command.   The only thing you can't do is store the favorite position at the moment.

**Comment by Roku38** [comment]
This is great. 
Thank you very much @loucks1 and thank you for the quick response. Getting the parts tomorrow. hope all will go well.
